events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    proxy_cache_path /var/run/nginx-cache/jscache
        levels=1:2
        keys_zone=jscache:100m
        inactive=30d
        use_temp_path=off
        max_size=100m;

    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        resolver 1.1.1.1;

        location / {
            ssi on;
            index index.html;
        }
    }
}
